final version
nzlicrbc/InternTasks-1A pull request #2
Opened 2024-07-04 12:34 UTC by nzlicrbc

all updates done

2024-07-04 14:38 UTC, kerimisoffline requested changes
Yorumlara ek bir konu daha var. Bütün commitleri final commit olarak yazmışız. Commit isimlendirmesi önemli bir konu. Özellikle proje ve ekip büyüdükçe daha da önemi artıyor. Alışkanlık edinmek açısından kısaca o committe ne yaptığını örnekteki gibi yazabilirsin.
Örnek: Fix string name at MainActivity screen

Eline sağlık.

2024-07-04 14:38 UTC, kerimisoffline commented on app/src/main/res/layout/activity_main.xml
> +        android:text="İstanbul"
textlerin hepsini values/strings.xml dosyasından okuyalım.

2024-07-04 14:38 UTC, kerimisoffline commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/weather_icon"
isimlendirmede belli bir standart üzerinden devam etmeni öneriyorum.
1. seçenek yukarıda yaptığın gibi "tv_day" şeklinde. o zaman bu satırda "iv_weather" şeklinde düzeltebiliriz.
2. seçenek tüm id'leri camel case yani "textViewDay" yada "imageViewWeather" şeklinde de yapabilirsin. bu seçenek şahsi tercihim.
Önemli olan uygulamada bütün heryer'in aynı formatta olması.

2024-07-04 14:38 UTC, kerimisoffline commented on app/src/main/res/values-night/themes.xml
> +        <item name="android:iconTint">@color/white</item>
requires API level 26 (current min is 24) uyarısı veriyor.

2024-07-04 14:38 UTC, kerimisoffline commented on app/src/main/res/layout/activity_main.xml
> +        />
Format kod yaptım ve 40 satır düzenledi otomatik olarak. Kullanmayı alışkanlık haline getirmek güzel olur.
Aşağıdaki kısayollar ile xml dosyası içerisindeyken yapabilirsin.
Windows: Control+Alt+L
Mac: Command+Option+L

2024-07-04 14:38 UTC, kerimisoffline commented on app/src/main/res/layout/activity_main.xml
>      <!-- TODO Design task-1 screen here -->
Yorum satırını silebiliriz.

2024-07-05 10:48 UTC, TamerSarioglu commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Bugün"
Burayı ve eğer alt tarafta hard coded string varsa strings dosyasından çağırabiliriz.

2024-07-05 10:48 UTC, TamerSarioglu approved these changes

2024-07-05 10:51 UTC, nzlicrbc commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Bugün"
android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:fontFamily="sans-serif"
        android:text="@string/day"
 Bende bu şekilde görünüyor neden olmuş olabilir?

2024-07-05 11:51 UTC, kerimisoffline commented
Chain kullanımın doğru gözüküyor fakat uygulamayı çalıştırıp baktığımda ikonlar alt alta gelmemiş. Tasarımda alt alta gelmesi bekleniyor. Şuanki kullanımda bunu yapabilmen mümkün ama uğraştıracaktır. Yada projeni bir önceki commit'e döndürebilirsin. Bunu yapabilmen için ipucu (how to hard reset to spesific commit). Bu ikisinden birini yaptığında onaylayıp taskı bitirebiliriz. Eline sağlık. @nzlicrbc

2024-07-05 14:20 UTC, kerimisoffline approved these changes
Eline sağlık

2024-07-05 14:41 UTC, akndmr approved these changes
Eline sağlık 🍏 
Gerekli yorumlar yapılmış zaten, hepsini de halletmişsin. Kod olarak da gayet temiz olmuş.

2024-07-08 06:38 UTC, merged